spring:
  profiles:
    active: prod
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev
    default-schema: public
    enabled: true
  jpa:
    open-in-view: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"